[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc_version = "0.8.20"
optimizer = true
optimizer_runs = 200
sender = "0x1e126bE111595223898344f67E4D60d0913d487d" 

[rpc_endpoints]
tenderly = "https://virtual.mainnet.rpc.tenderly.co/2e66079c-55ba-4504-837a-ac7ec899444f"


# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
